### ISSUE TITLE
How to run the tutorial or notebooks from this repo

### ISSUE THREAD

**Issue by guillaumeeb** [pangeo-data/foss4g-2022#21]
There should be a how to run things section somewhere. I think this is foreseen and intended to go there: https://pangeo-data.github.io/foss4g-2022/before/setup.html, am I right?

I propose to put the following content:

- Running on Binderhub
- Running locally on personal computer
- Running on Pangeo EOSC infrastructure

Thoughts?

**Comment by guillaumeeb** [comment]
We also need to precise what Sebastian told us:

> 2. If you connect DaskHub with Check-In, prior to the FOSS4G workshop, all users will have to 1) Create an account on the development instance of Check-In, clicking on: https://aai-dev.egi.eu/registry/co_petitions/start/coef:2, 2) enroll the "[vo.pangeo.eu](http://vo.pangeo.eu/)" Virtual Organisation clicking on: https://aai-dev.egi.eu/registry/co_petitions/start/coef:290. This means that VO managers (Tina, Lorenzo, Anne, Jean) will need to approve the petition to join from all trainees.

**Comment by guillaumeeb** [comment]
In the xarray_hand_on notebook, we also use 

```python
session = openeo.connect("https://openeo.vito.be").authenticate_oidc(provider_id="egi")
```

This means that participant should also have an EGI Check-in account from the operational instance.

**Comment by pl-marasco** [comment]
> In the xarray_hand_on notebook, we also use
> 
> ```python
> session = openeo.connect("https://openeo.vito.be").authenticate_oidc(provider_id="egi")
> ```
> 
> This means that participant should also have an EGI Check-in account from the operational instance.

You have a point on this; that's why, as well for other reasons,  a new approach has been taken. 
I would suggest you to refer to the new training material [here](https://github.com/pangeo-data/foss4g-2022/tree/main/tutorial/pangeo101)  even if isn't fully polished.

**Comment by guillaumeeb** [comment]
Thanks for the pointer @pl-marasco! Your comment is also linked to #22, I'm not sure if the notebooks in NOTEBOOK need to be kept, and what notebooks should I look at if I wanna help. I see you also closed #13, not sure why?

Anyway I'll look in the tutorial folder from now on. 

And to focus on this issue subject, are you all okay with the proposed content of "how to run the tutorial" ?

**Comment by pl-marasco** [comment]
@guillaumeeb indeed the comment is linked to #22 but I didn't answer directly to that one as @annefou is re-organizing the entire material.
I see your point regarding the necessity of simplifying the structure and removing the notebook. Although keeping a more detailed notebook might be helpful if not all aspects are covered during the course. I would also change the content a little bit removing the makeup components. 

The #13 has been removed in the vision of the material reorganization. 

Agree with the necessity to add an explanation on how to run the material over different platforms. I would only switch the order:

- Pangeo EOSC 
- locally 
- Binderhub

**Comment by guillaumeeb** [comment]
👍 on the order.

Is I ok for everyone if I work on this today or tomorrow?

**Comment by acocac** [comment]
Just to add, the Jupyter book allows adding a JupyterHub (see [here](https://jupyterbook.org/en/stable/interactive/launchbuttons.html#add-a-launch-on-jupyterhub-button)). Are we aiming to add the Pangeo EOSC there?

**Comment by acocac** [comment]
For Binder, I'd suggest testing the GESIS binder which has a larger memory than the standard Binder.
