### ISSUE TITLE
Where should the Notebooks go?

### ISSUE THREAD

**Issue by guillaumeeb** [pangeo-data/foss4g-2022#22]
Currently, there are two main folders: NOTEBOOKS (not fond of the upper case style), and tutorial. In tutorial: notebooks.

I'm under the impression that all notebooks that workshop participants want to see should be in tutorial/notebooks.

If so, we should move important content from NOTEBOOKS folder to tutorial/notebooks, and either remove the NOTEBOOKS folder, or rename it in a way it is clear that its content is not important for learning about Pangeo.

Anyway, I think we should clarify things here.

**Comment by acocac** [comment]
@guillaumeeb the NOTEBOOK folder is temporal. We can rename and keep it as a miscelaneous folder with unfinished notebooks.

**Comment by pl-marasco** [comment]
I fully support the idea of @guillaumeeb start cleaning up a little bit. 
I would also suggest to take a decision regarding the monolithic notebook. 
from my perspective here are the options:
 
- keep it as it is. 
- remove all the unnecessary redundancy components that I added and keep it as bonus material.
- remove completely and rely only on the tutorial version.  

I would vote for the second one but at the same time maybe would be better to focus on something that is more useful for the partecipants.

@guillaumeeb  @acocac  @tinaok @annefou  how about these options?

**Comment by annefou** [comment]
The notebooks are not meant to be used for the workshop. We used them to derive the training material. They could showcase complete use cases using best practices and could be re-used by attendees for their own use cases. The initial idea was to create FAIR Digital Object for each of these notebooks that can be easily found for instance in EOSC Explore. This is also to give more visibility to the authors of these notebooks as individual contribution.

**Comment by guillaumeeb** [comment]
I would at least rename the folder to something that says clearly this is not the principal content, as @acocac proposed.

Maybe dev-material, or misc, I've trouble finding the correct term.

**Comment by annefou** [comment]
what about example or showcase osr use-case?

**Comment by pl-marasco** [comment]
Whatever the name will be, can we move the folder from ./NOTEBOOK to ./tutorial/notebooks?

Exercise declined in the meaning of an activity carried out for a specific purpose could be another option.

**Comment by annefou** [comment]
Following your suggestion, I created a PR #44
