### ISSUE TITLE
Do we need a Setup chapter in the tutorial notebooks?

### ISSUE THREAD

**Issue by guillaumeeb** [pangeo-data/foss4g-2022#49]
We already have a [main setup page](https://pangeo-data.github.io/foss4g-2022/before/setup.html) and an environment.yaml file.

Is this really important that each of our notebooks list the main libraries it needs? 

How do we chose the libraries we put there: those which are imported in cells? Those for which we uses some objects one way or another?

I understand that we may want each notebook to contains every information to run it, but this section is really hard to maintain, and maybe we should just link to the setup page and the environment.yaml?

**Comment by annefou** [comment]
The main goal was to promote the citation of the main packages used in the notebook.

**Comment by acocac** [comment]
@guillaumeeb, the main goal is to promote the citation of packages as academics usually cite their publications (see #17). 

We'll add the references at the end of each notebook once we have the final version of the jupyter book.

**Comment by guillaumeeb** [comment]
Okay, that makes a lot of sens!!

So this should contain libraries that are imported at least, and if possible other main package that it depends on.

Maybe we should rename the section.

Main packages used
Packages citations
External libraries

I haven't really good ideas...

**Comment by annefou** [comment]
Can we close this issue? @acocac added citations for the main packages used in each notebook

**Comment by acocac** [comment]
I'd suggest closing it. I hope the packages citation section in each episode is ok for @guillaumeeb.

**Comment by guillaumeeb** [comment]
I would just have renamed the section, _Packages_ or _Package citation_, but this really is a minor issue, and it's fine to leave it as is.
