### ISSUE TITLE
Update content of dask_introduction.ipynb

### ISSUE THREAD

**Issue by guillaumeeb** [pangeo-data/foss4g-2022#50]
Here are some propositions as discussed in https://github.com/pangeo-data/foss4g-2022/pull/45.

Please indicate whether it's OK for you (especially @tinaok):

- [x] Add a little part on Dask Clusters, talk about Client, Scheduler, Worker, dask-gateway, Kubernetes, HPC. Only quick words on the last terms. Talk about Dask Dashboard (which needs to be accessible in the platforms we propose).
  - Maybe we wan to do a short demonstration of Dask and its Dashboard on some code independent of our dataset?
- [x] Is the call to optimize for the Dask graphs really important? I find it weird, you don't need this with Dataframes.
- [x] Remove the part about installing packages on worker pods. I think this is an advanced topic and should not be usefull if we fix https://github.com/pangeo-data/pangeo-eosc/issues/3.
- [x] Add some code at the end with the global scaling of some process as announced in the beginning of the notebook.

**Comment by annefou** [comment]
@annefou will add explicitely dask local (with sub-title) instead of having embedded.

Will also check once we have the infra ready.

**Comment by tinaok** [comment]
>Is the call to optimize for the Dask graphs really important? I find it weird, you don't need this with Dataframes.
Yes with Xarray it dramatically change.  
> Remove the part about installing packages 
same as Anne's comment we need to wait that infra is ready.
>Add some code at the end with the global scaling 
We might limit the contents due to our 4 hour time limit.

**Comment by guillaumeeb** [comment]
I addressed some point in #83. But there are still discussion to have:

- Warning on spilling, I think this is too complex to introduce yet.
- dask.optimize(): should we really introduce this? This makes a different in number of tasks displayed, but upon execution, Dask is clever enough to not execute the useless tasks, I tested with and without optimization on graph, and the result is almost the same. I'm under the impression that Dask does optimize things anyway upon calling compute.

You can have a look to the review I made in #83 for detailed pointers of what I'm talking about.
