### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by annefou** [pangeo-data/foss4g-2022#54]
Add timeline + names (who is teaching what).

**Comment by acocac** [comment]
| Duration | Activity | 
| ---- | -------- | 
| Start | 👋 Welcome | 
| 5 mins | Introductions and workshop goal setting |
| 60 mins | Handling multi-dimensional arrays with xarray |
| 30 mins | Interactive plotting with HoloViews |
| 5 mins | ☕️ Break |
| 60 mins | Data access & Data chunking |
| 60 mins | Parallel computing with Dask |
| 5 mins | ☕️ Break |
| 30 mins | Data discovery (optional) |
| 15 mins | Concluding remarks & Q&A |
