### ISSUE TITLE
Resources in BEYOND THE WORKSHOP

### ISSUE THREAD

**Issue by acocac** [pangeo-data/foss4g-2022#66]
Please type here additional resources you consider relevant to highlight in the **Beyond the workhop section**.

**Comment by acocac** [comment]
Proposed sections:

# Pangeo cloud infrastructure
- [2i2c JupyterHub](https://us-central1-b.gcp.pangeo.io/hub/login?next=%2Fhub%2F): it's a pilot cloud infrastucture which serve Pangeo on open source infrastructure. Find further details of the partnership [here](https://2i2c.org/blog/2021/pangeo-goes-live/).

# Notebooks and other interesting resources

**Comment by acocac** [comment]
**TODO**

- Add the URL for the main Pythia site (see https://github.com/ProjectPythia/projectpythia.github.io/discussions/273).

**Comment by guillaumeeb** [comment]
Maybe a link to Pangeo medium blog page?

Other than that, that seems already pretty complete!
